// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemav5.Models;

namespace sistemav5.Migrations
{
    [DbContext(typeof(sistemav5Context))]
    [Migration("20190820125756_v5.0.4")]
    partial class v504
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sistemav5.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<int>("PedidoId");

                    b.Property<int>("Telefone");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("sistemav5.Models.ItensPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProdutoId");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("sistemav5.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId");

                    b.Property<int?>("ClienteIdCliente");

                    b.Property<int>("ItensPedidoId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("ItensPedidoId")
                        .IsUnique();

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("sistemav5.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItensPedidoId");

                    b.Property<string>("Nome");

                    b.Property<double>("Preco");

                    b.Property<int>("Quantidade");

                    b.HasKey("IdProduto");

                    b.HasIndex("ItensPedidoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("sistemav5.Models.Pedido", b =>
                {
                    b.HasOne("sistemav5.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("sistemav5.Models.ItensPedido", "ItensPedido")
                        .WithOne("Pedido")
                        .HasForeignKey("sistemav5.Models.Pedido", "ItensPedidoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sistemav5.Models.Produto", b =>
                {
                    b.HasOne("sistemav5.Models.ItensPedido")
                        .WithMany("Produtos")
                        .HasForeignKey("ItensPedidoId");
                });
#pragma warning restore 612, 618
        }
    }
}
